location
url = "https://huggingface.co/BAAI/bge-reranker-base/resolve/2cfc18c9415c912f9d8155881c133215df768a70/model.safetensors?download=true"
range = "0-139025767"
output = "D:/python_projects/tsinghua_ai/data_second/rag_v1/indexes/reranker/_download_parts/part-00.bin"
next
location
url = "https://huggingface.co/BAAI/bge-reranker-base/resolve/2cfc18c9415c912f9d8155881c133215df768a70/model.safetensors?download=true"
range = "139025768-278051535"
output = "D:/python_projects/tsinghua_ai/data_second/rag_v1/indexes/reranker/_download_parts/part-01.bin"
next
location
url = "https://huggingface.co/BAAI/bge-reranker-base/resolve/2cfc18c9415c912f9d8155881c133215df768a70/model.safetensors?download=true"
range = "278051536-417077303"
output = "D:/python_projects/tsinghua_ai/data_second/rag_v1/indexes/reranker/_download_parts/part-02.bin"
next
location
url = "https://huggingface.co/BAAI/bge-reranker-base/resolve/2cfc18c9415c912f9d8155881c133215df768a70/model.safetensors?download=true"
range = "417077304-556103071"
output = "D:/python_projects/tsinghua_ai/data_second/rag_v1/indexes/reranker/_download_parts/part-03.bin"
next
location
url = "https://huggingface.co/BAAI/bge-reranker-base/resolve/2cfc18c9415c912f9d8155881c133215df768a70/model.safetensors?download=true"
range = "556103072-695128839"
output = "D:/python_projects/tsinghua_ai/data_second/rag_v1/indexes/reranker/_download_parts/part-04.bin"
next
location
url = "https://huggingface.co/BAAI/bge-reranker-base/resolve/2cfc18c9415c912f9d8155881c133215df768a70/model.safetensors?download=true"
range = "695128840-834154607"
output = "D:/python_projects/tsinghua_ai/data_second/rag_v1/indexes/reranker/_download_parts/part-05.bin"
next
location
url = "https://huggingface.co/BAAI/bge-reranker-base/resolve/2cfc18c9415c912f9d8155881c133215df768a70/model.safetensors?download=true"
range = "834154608-973180375"
output = "D:/python_projects/tsinghua_ai/data_second/rag_v1/indexes/reranker/_download_parts/part-06.bin"
next
location
url = "https://huggingface.co/BAAI/bge-reranker-base/resolve/2cfc18c9415c912f9d8155881c133215df768a70/model.safetensors?download=true"
range = "973180376-1112206139"
output = "D:/python_projects/tsinghua_ai/data_second/rag_v1/indexes/reranker/_download_parts/part-07.bin"
